notifications:
    email:
        recipients:
            - glance@acc.umu.se

os:
    - linux

language: c

cache:
    directories:
        - android-ndk-r13b

addons:
    apt:
        packages:
            - intltool
            - autopoint

env:
    - TARGET="arm"
    - TARGET="x86"
    - TARGET="x86_64"

before_install:
    - if [ ! -e android-ndk-r13b/toolchains ] ; then
        curl -Lk http://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip -o android-ndk.zip ;
        unzip -q android-ndk.zip ;
      fi
    - export ANDROID_NDK_ROOT=$PWD/android-ndk-r13b

script:
    bash build.sh $TARGET
